version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PARKING_API_PORT: 8080
      JDBC_USER: postgres
      JDBC_PASSWORD: password
      JDBC_URL: jdbc:postgresql://database:5432/parking
    ports:
      - "8080:8080"
    depends_on:
      - database
    links:
      - database

  database:
    image: "postgres:14.0"
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: parking
    volumes:
      - postgres-volume:/var/lib/postgresql/data/

volumes:
  postgres-volume:
