version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parking_backend
    environment:
      JDBC_USER: postgres
      JDBC_PASSWORD: password
      JDBC_URL: jdbc:postgresql://parking_database:5432/parking
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - common

  database:
    image: "postgres:14.0"
    container_name: parking_database
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: parking
    volumes:
      - postgres-volume:/var/lib/postgresql/data/
    networks:
      - common

volumes:
  postgres-volume:

networks:
  common:
