parking:
  floor:
    height:
      min: 2.5
      max: 5.0
    weight:
      min: 100.0
      max: 500.0
  ticket:
    price:
      avg: 100.0
      strategy:
        default: ${DEFAULT_PRICING_STRATEGY:FLOOR_OCCUPANCY}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:password}
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/parking}
    hikari:
      autocommit: false
      connection-timeout: 5000
      maximum-pool-size: 15
  jpa:
    show-sql: true
    properties.hibernate.dialect: ${DB_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQL10Dialect}
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.types.print.banner: false
      hibernate.default_schema: ${DATABASE_SCHEMA:public}
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

server:
  port: ${PORT:8080}
  tomcat:
    max-swallow-size: 5MB
    connection-timeout: 5s
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /api

management:
  endpoint:
    health:
      show-details: always
